apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: demo
  name: demo

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: test
  name: test

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: branch
  name: branch
